#!bash
#./main.py $1 | ./youtube-dl --audio-format mp3 -o '%(title)s.%(ext)s' -x

path='~/data/data/com.termux/files/home/storage/music'

link=`python shazam-dl-termux/main.py "$1"`
echo $link
youtube-dl --audio-format mp3 -o "$path/%(title)s.%(ext)s" -x $link
