#!/data/data/com.termux/files/usr/bin/bash

echo 'Начинаем взлом пентагона...'
filename="${1::-4}.txt"
file=`cat "$filename"`
rm "$filename"
echo 'Перехват данных...'

echo 'Пентагон взломан'
echo 'Расшифровываем данные...'
bash shazam-dl-termux/shazam-dl "$file"
